### ISSUE TITLE
Заголовки ETag и Cache-Control, чтобы позволить клиентам кэшировать запросы.

### ISSUE THREAD

**Issue by SashaXser** [FOSWLY/translate-backend#4]
HTTP определяет некоторые заголовки, позволяющие серверам передавать требования к кэшированию клиентам, а клиентам - указывать серверам, что у них есть определенный ресурс в кэше. Например, если сервер включает заголовок ETag и заголовок Cache-Control: public,max-age=3600,immutable, клиент не должен делать повторный запрос с тем же запросом в течение 3600 секунд. По истечении 3600 секунд, если клиент сделает еще один запрос с тем же запросом, он включит в запрос заголовок If-None-Match. Если сервер определит, что ресурс не был изменен, он может ответить сообщением 304 без тела ответа, чтобы указать клиенту, что кэшированный ресурс все еще свежий.

```mermaid
 sequenceDiagram
     Client->>+Server: GET /foo
     Server->>-Client: 200 OK, ETag: <A>, Cache-Control: ...
     note over Client,Server: Time Passes
     alt if server's resource is still fresh
     Client->>+Server: GET /foo, If-None-Match: <A>
     Server->>-Client: 304 Not Modified
     note over Client: Client uses cached resource
     else if server's resource has changed
     Client->>+Server: GET /foo, If-None-Match: <A>
     Server->>-Client: 200 OK, ETag: <A>, Cache-Control: ...
     note over Client: Client caches new version of resource
     end
 ```

**Comment by ilyhalight** [comment]
Сделал через CF, не думаю, что это должно быть на сервере

**Comment by SashaXser** [comment]
Сервер стал выдавать ошибку 520

**Comment by ilyhalight** [comment]
> Сервер стал выдавать ошибку 520, GET запрос не может обработать более 4кб Странно, но когда сам захостил, такой ошибки уже не было...

Похоже на какие-то лимиты cloudflare
